trigger:
- master

pool:
  name: agent

variables:
  dockerHubRepository: 'beelzekamibub/redisjava'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    repository: $(dockerHubRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(tag)
      latest

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: 'push'
    repository: $(dockerHubRepository)
    containerRegistry: 'dockerhub'
    tags: |
      $(tag)
      latest
