trigger:
- master

pool:
  name: agent   # Use your custom agent pool named 'agent'

variables:
  dockerHubRepository: 'beelzekamibub/myapp'   # Change 'myapp' to your preferred image name
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image to Docker Hub'
  inputs:
    command: 'build'
    repository: $(dockerHubRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(tag)
      latest
