apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis-pod
spec:
  containers:
  - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
    name: redis-pod
    imagePullPolicy: {{ .Values.image.pullPolicy }}
