apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis
  name: redis-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodeport }}
  selector:
    run: redis
  type: {{ .Values.service.type }}
